release:
        only:
                - master
        script:
                - if [ -d build ]; then echo "Build directory already exists"; else mkdir -p build; fi
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Release ..
                - nice -n 12 cmake --build .
                - nice -n 12 cmake --build . --target checks
                - mv circle ..
                - iconv -c -f utf8 -t koi8-r changelog > ../changelog
        cache:
                key: "$CI_BUILD_REF_NAME/Release"
                untracked: true
                paths:
                        - build/
        artifacts:
                name: "circle-release"
                paths:
                        - circle
                        - changelog
                expire_in: 1 week
        tags:
                - builder

debug:
        script:
                - if [ -d build ]; then echo "Build directory already exists"; else mkdir -p build; fi
                - cd build
                - cmake -DCMAKE_BUILD_TYPE=Debug ..
                - nice -n 12 cmake --build .
                - nice -n 12 cmake --build . --target checks
                - mv circle ..
                - iconv -c -f utf8 -t koi8-r changelog > ../changelog
        cache:
                key: "$CI_BUILD_REF_NAME/Debug"
                untracked: true
                paths:
                        - build/
        artifacts:
                name: "circle-debug"
                paths:
                        - circle
                        - changelog
                expire_in: 1 week
        tags:
                - builder

deploy-debug:
        stage: deploy
        script:
                - echo "Deploying debug build..."
        dependencies:
                - debug
        script:
                - rm -rf ${BYLINS_DEBUG_HOME}/circle || true
                - cp -af circle ${BYLINS_DEBUG_HOME}
                - rm -rf ${BYLINS_DEBUG_HOME}/changelog || true
                - cp -af changelog ${BYLINS_DEBUG_HOME}
                - touch ${BYLINS_DEBUG_HOME}/lib/external.triggers/touch.me.for.reboot
        when: manual
        tags:
                - mirror

deploy-release:
        only:
                - master
        stage: deploy
        script:
                - echo "Deploying release build..."
        dependencies:
                - release
        script:
                - rm -rf ${BYLINS_RELEASE_HOME}/circle || true
                - cp -af circle ${BYLINS_RELEASE_HOME}
                - rm -rf ${BYLINS_RELEASE_HOME}/changelog || true
                - cp -af changelog ${BYLINS_RELEASE_HOME}
                - touch ${BYLINS_RELEASE_HOME}/lib/external.triggers/touch.me.for.reboot
        when: manual
        tags:
                - mirror
